apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: settings-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: managed-nfs-storage
