apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: maximo-ai-agent
    component: app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
spec:
  selector:
    app: maximo-ai-agent
    component: mcp-server
  ports:
    - name: http
      port: 8081
      targetPort: 8081
